const express=require('express')
const app=express()

const cors=require('cors')
require('./conn/conn')
const user=require('./routes/user')
const Favourite=require('./routes/favourite')
const Book=require('./routes/book')
const Cart=require('./routes/cart')
const Order=require('./routes/order')
app.use(express.json())
app.use(cors())
app.use("/api/v1",user)
app.use("/api/v1",Book)

app.use("/api/v1",Favourite)
app.use("/api/v1",Cart)
app.use("/api/v1",Order)
app.listen(8000,()=>{
    console.log("server stated")
})